### ISSUE TITLE
Tried to load to Firefox but has errors

### ISSUE THREAD

**Issue by p2635** [tourdedave/selenium-ide-plugins#1]
![image](https://user-images.githubusercontent.com/4522927/59100210-410def80-891d-11e9-9d9d-6d3320f7b7d5.png)

**Comment by p2635** [comment]
However, it looks like I can see the icon on Firefox, I've yet to test the actual plugin but just flagging those errors to you.

**Comment by tourdedave** [comment]
Please try the plugin and let me know if it works for you even with the errors

**Comment by p2635** [comment]
I commented on https://github.com/SeleniumHQ/selenium-ide/issues/183.

Would you be able to send me the csv file that goes along with the sample project you provided? Is it literally a column with username and a column for password?

**Comment by qatestchannelass** [comment]
Have the same problem in Firefox

![Capture](https://user-images.githubusercontent.com/50674510/61076193-ac9a1f80-a3e9-11e9-9f9e-909b82bc835b.JPG)

**Comment by qatestchannelass** [comment]
I have the same problem in Firefox.

![Capture](https://user-images.githubusercontent.com/50674510/61076482-5e395080-a3ea-11e9-91cc-e889cef2ba1a.JPG)

**Comment by qatestchannelass** [comment]
I got the error in Chrome.
![CaptureChrome](https://user-images.githubusercontent.com/50674510/61076941-5cbc5800-a3eb-11e9-9bd6-90309bd7fe15.JPG)

**Comment by qatestchannelass** [comment]
For me this plugin does not work.
Please take a look.
Thank you.

**Comment by sartajsgill** [comment]
Yes, did not work for me either in Firefox or Chrome. Looked at the manifest.json file . That file points to assets/... folder but I don't see that folder. I see an app folder, background folder, content folder. So maybe it is setup incorrectly in the manifest file. Also I think the index.html file does not have anything in it, maybe it is getting loaded via js, not sure.

**Comment by tourdedave** [comment]
@p2635 Those look to be warnings, not errors. The plugin still loads.

Here's an example CSV file:

```
a,b,c
1,2,3
```

Although I'll need to make a change to support the new collection format expected by forEach in Selenium IDE.

**Comment by tourdedave** [comment]
@qatestchannelass Try using the release version from [here](https://github.com/tourdedave/selenium-ide-plugins/releases/latest). Specifically [`file-upload.zip`](https://github.com/tourdedave/selenium-ide-plugins/releases/download/v0.1.0/file-uploader.zip), not the source code zips.

**Comment by p2635** [comment]
I haven't been using Selenium IDE for a while so I might not get to this straight away. If anyone wants to check this out, they can and I am happy for them to close it if they are able to confirm there are no problems.

**Comment by sirteace** [comment]
I get the same error as @catestchannelass for the Chrome extension. 

![image](https://user-images.githubusercontent.com/55513270/65185555-7b387280-da70-11e9-991d-2602e0a9acf6.png)

When I try to run the data-driven.side in Selenium IDE, it throws me the following error when trying to add the username and password. I believe this is because the fileContents are not read in. I have created the sample.csv both from google sheets (comma separated) and from excel (semicolon separated). So either the plugin does not work at all (although it adds the name of the file in the top bar) or somehow it just does not load the csv file. 

![image](https://user-images.githubusercontent.com/55513270/65185467-4cba9780-da70-11e9-92e0-076591782e74.png)

Any ideas what I should do to make it work? Any help is very much appreciated. Thanks in advance!

**Comment by sirteace** [comment]
> Although I'll need to make a change to support the new collection format expected by forEach in Selenium IDE.

@tourdedave When do you expect to make those changes? It seems that data-driven.side will not run without them at all. I have downloaded the newest release (.zip) version of the plugin (May 23rd) as you suggested earlier.

**Comment by yzong0107** [comment]
Hi @tourdedave , I have same issue with @surveytester 

executeScript on return ${iterator}.username with value username Failed:
Unexpected token '{'
'with-file-uploader' ended with 1 error(s)

Will it be fixed in the future? I'm using Chrome and downloaded the newest release (.zip) v0.1.0.

Thanks,

**Comment by sprathi-mn** [comment]
Hi 

I also got the Issue "Unexpected token '{' " when we execute script with for each iteration

Not able to proceed on this.

Hope this will be fixed in near future
